"""Data models for worktree isolation."""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field


class WorktreeResult(BaseModel):
    """Returned by WorktreeProxy.take_result() when writes occurred."""

    model_config = ConfigDict(extra="forbid")

    id: str
    worktree_path: Path
    workspace_root: Path
    changed_files: list[str]
    diff: str
    agent_name: str
    is_git: bool


class WorktreeRecord(BaseModel):
    """Manifest entry tracking worktree lifecycle."""

    model_config = ConfigDict(extra="forbid")

    id: str
    worktree_path: Path
    workspace_root: Path
    agent_name: str
    created: datetime
    status: str  # "pending" | "merged" | "discarded"
    is_git: bool
    branch_name: str | None = None


# Regex pattern for extracting worktree ID from agent response text.
# Must match the format generated by MicroAgent._handle() (agents/micro.py:92).
# Used by ForkRunner to correlate fork branches with their worktrees.
WORKTREE_MERGE_PATTERN: str = r"signal worktree merge (wt_[a-f0-9]+)"


class ForkResult(BaseModel):
    """Result of a single fork branch execution."""

    model_config = ConfigDict(extra="forbid")

    branch_index: int
    task_description: str
    response: str
    worktree_id: str | None = None
    changed_files: list[str] = Field(default_factory=list)
    success: bool
    error: str | None = None
